### ISSUE TITLE
Why isn't this in core??

### ISSUE THREAD

**Issue by zdkroot** [ybr-nx/laravel-mariadb#1]
I just ran into this issue today and can hardly believe Laravel doesn't handle it already. If you haven't you should PR this. Thanks so much!

**Comment by hariesnurikhwan** [comment]
+1 This should be in core.

**Comment by george-kar** [comment]
Did you made a pull request on laravel?

**Comment by ybr-nx** [comment]
https://github.com/laravel/framework/pull/24546

I'll close this one
