### ISSUE TITLE
Problems with unquoting

### ISSUE THREAD

**Issue by buddhaCode** [ybr-nx/laravel-mariadb#19]
Thanks four your great grammar!

I have some problems with the unquoting. I have the following JSON doc in a column:

```json
{ "displayName": "App\\Jobs\\rotateClip" }
```

When querying this property I will get the quoted return: `"App\\Jobs\\rotateClip"`
I could use `->>` to unquote it. But then my code wouldn't be database agnostic anymore. On a MySQL Database this would fail. And MySQL is unquoting it by default. Shouldn't this behavior be the same on MariaDB?

**Comment by ybr-nx** [comment]
What's the version of MariaDB server?

**Comment by ybr-nx** [comment]
Can it be related to the last section of this one?
https://github.com/ybr-nx/laravel-mariadb/blob/master/README.md

**Comment by buddhaCode** [comment]
It's version 10.3.15. So the bug should be fixed in my version.
